name: Deploy Frontend to DigitalOcean

on:
  push:
    branches:
      - feature-billing
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_FRONTEND_IP }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          command_timeout: 60m
          script: |
            mkdir -p /app
            cd /app
            if [ ! -d ".git" ]; then
              rm -rf ..?* .[!.]* *
              git clone --single-branch --branch feature-billing https://github.com/${{ github.repository }}.git .
            else
              git fetch origin feature-billing
              git reset --hard origin/feature-billing
            fi
            echo "${{ secrets.FRONTEND_ENV }}" > .env
            docker compose up -d --build
